### ISSUE TITLE
BeagleBone default i2c busnum should be 2

### ISSUE THREAD

**Issue by pdp7** [adafruit/Adafruit_Python_BNO055#10]
The default i2c `busnum` used by this library on the BeagleBone should be `2` as pins [`P9_19` _(`I2C2_SCL`)_ and `P9_20` _(`I2C2_SDA`)_](http://beagleboard.org/static/images/cape-headers.png) are accessed via the device `/dev/i2c-2`.

Please see this Adafruit forum issue for more information:
[Error when trying to run BNO055 simpletest.py](https://forums.adafruit.com/viewtopic.php?f=49&t=122596)

**Comment by caternuson** [comment]
I think this is fixed by Blinka? If not, please reopen there.
https://github.com/adafruit/Adafruit_Blinka
