### ISSUE TITLE
Can you also make this available on platforms other than linux?

### ISSUE THREAD

**Issue by walchko** [adafruit/Adafruit_Python_BNO055#2]
Since you can talk to the IMU via a serial connection, I have successfully used it on OSX. Mabe Windoze will work too? However your setup file requires Adafruit-GPIO which won't install on OSX because of spidev looking for linux header files. Is there a way to conditionally change this (or maybe Adafruit-GPIO ) so BNO055 package will install on OSX? It would be nice to stay up to date via `pip` rather than me manually checking for updates to this package.

**Comment by ladyada** [comment]
how would you do i2c on macos?

**Comment by walchko** [comment]
you are correct … no i2c, but the serial connection works. You just can't install the package because of the i2c requirements. Not sure if my request is easy or complex or the best way to maybe do it.

**Comment by ladyada** [comment]
ooh - its...low on our to do list - no ETA, may not ever get to it :/

**Comment by caternuson** [comment]
Keep an eye on this library:
https://github.com/adafruit/Adafruit_Blinka

If it has hardware support for your platform, you can use this library:
https://github.com/adafruit/Adafruit_CircuitPython_BNO055
