### ISSUE TITLE
Register Write Error: 0x6e06

### ISSUE THREAD

**Issue by jinzhong012** [adafruit/Adafruit_Python_BNO055#5]
Hi, 

I just followed the instruction and installed the BNO055 Python Module on Raspberry Pi Zero. However, when I tried to run the simpletest.py, it showed "RuntimeError: Register read error: 0x6e06". It seems that it tried to read data from a non-existing register.  If I keep running the simpletest.py several times, it may work a few seconds and then show another "Register read error" again.

Could you please tell me whether there is anything I can do to solve this problem?

Thanks a lot.

**Comment by Bob1908** [comment]
I got the same trouble on PI 3.  For me when it works it works, but it work only 1 time on 2 that problematic for my application. Someone knows why? and has a way to solve that? Or maybe a way to run again the scrip after the error?

Thanks!

**Comment by Sailanarmo** [comment]
Can confirm that this is also an Issue on the Raspberry Pi 3. I have disabled everything that I needed to disable in order to talk to the serial bus. However, when I run the code I get Register Write error. Is this going to be addressed at all for those of us who are depending on this sensor for research?

**Comment by ladyada** [comment]
@Sailanarmo its the sensor out of sync, just rerun the code again

**Comment by Sailanarmo** [comment]
@ladyada I actually had to diasble bluetooth in order for this error to go away. I am in the process of trying to debug why I am not getting a response back from the sensor when I have the wiring in the exact same way as the image from the tutorial. However, I believe that is something that can be discussed on the official forums.

**Comment by caternuson** [comment]
RPi support is now covered by using the Blinka library:
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/overview
with the CircuitPython library:
https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/python-circuitpython

Please switch to using the BNO055 via that approach and if you continue to have issue, open them in the repo for the new library:
https://github.com/adafruit/Adafruit_CircuitPython_BNO055
