### ISSUE TITLE
Register write error exception thrown regardless of ack=True in _write_bytes()

### ISSUE THREAD

**Issue by ServerTech** [adafruit/Adafruit_Python_BNO055#6]
In _write_bytes() in BNO055.py, the response from the serial send function is being checked regardless of whether ack was set to True. Might be the source of some register write error exceptions!

**Comment by udusa** [comment]
In BNO005.py line 241 , "if i2c is None:" should be "if i2c is not None:".

**Comment by caternuson** [comment]
This driver is being deprecated. The new one handles this transaction differently. Please switch to the new driver:
https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/python-circuitpython
and if the problem persists, then re-open this issue in the new driver repo:
https://github.com/adafruit/Adafruit_CircuitPython_BNO055
