### ISSUE TITLE
I2C connection error

### ISSUE THREAD

**Issue by vladlanda** [adafruit/Adafruit_Python_BNO055#9]
In BNO005.py line 241 , "if i2c is None:" should be "if i2c is not None:".

**Comment by caternuson** [comment]
Why?
The idea is to check if an i2c object was passed in on creation and if not then create one.

**Comment by vladlanda** [comment]
What should be passed as 'i2c'?, As for the serial its pretty clear but its
not clear for the i2c because its not a path, it should be an object from
the library, hence much more convenient to leave the 'i2c' as none by
default​ and create it if 'serial' is none.
Best regards.

**Comment by caternuson** [comment]
That is the behaviour.

**Comment by vladlanda** [comment]
Ok, by the way great job and thanks.
I just had some difficulty configurate it right.
